config/routes.rb
Omrails::Application.routes.draw do
  get 'about' => 'pages#about'
  get 'videos' => 'pages#videos'

  root :to => 'pages#home'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def action
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_footer.html.erb
<div class="footer">
	<small>
	<%= link_to "Shotgun Software", "http://shotgunsoftware.com" %>
	is the link to the website of the company I work for.
	<%= link_to "Ruby on Rails", "http://rubyonrails.org" %>
	is the software I'm using for this...
	</small>
<div/>

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
 
      <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>

      <a class="brand" href="#">Shotgun Support</a>
 
      <!-- Everything you want hidden at 940px or less, place within here -->
      <div class="nav-collapse collapse">
      	<ul class="nav">
	      	<li><%= link_to "Home", root_path %></li>
					<li><%= link_to "About", about_path %></li>
          <li><%= link_to "Videos", videos_path %></li>
				</ul>
				<ul class="nav pull-right">
	      	<li><%= link_to "Login", ''%></li>
				</ul>
        
      </div>
 
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>Support vid testbed</title>
	  <%= stylesheet_link_tag    "application", :media => "all" %>
	  <%= javascript_include_tag "application" %>
	  <%= csrf_meta_tags %>
	</head>
	<body>
		<%= render 'layouts/header' %>
		
		<div class="container">
		<%= yield %>

		<%= render 'layouts/footer' %>
			
	</body>
</html>

app/views/pages/about.html.erb
<h1>About</h1>
<p>
	about us... something awfully poignant about us...
</p>

app/views/pages/home.html.erb
<div class="hero-unit">
	<h1>Shotgun Support Videos</h1>
	<p>
		Mason's support video experiment. Looking for the 
		<%= link_to "Shotgun website", "http://shotgunsoftware.com" %>
		?
	</p>
	<p>
		<%= link_to "Sign up now!", '' %>


</div>

<ul class="thumbnails">
  <li class="span4">
    <div class="thumbnail">
      <img data-src="holder.js/300x200" alt="">
      <h3>Thumbnail one</h3>
      <iframe src="https://fast.wistia.net/embed/iframe/l8emkgdbny?videoFoam=true" allowtransparency="true" frameborder="0" scrolling="no" class="wistia_embed" name="wistia_embed" allowfullscreen mozallowfullscreen webkitallowfullscreen oallowfullscreen msallowfullscreen width="640" height="360"></iframe><script src="//fast.wistia.net/assets/external/iframe-api-v1.js"></script>
      <p>Thumbnail one caption...</p>

      <img data-src="holder.js/300x200" alt="">
      <h3>Thumbnail two</h3>
      <iframe src="https://fast.wistia.net/embed/iframe/l8emkgdbny?videoFoam=true" allowtransparency="true" frameborder="0" scrolling="no" class="wistia_embed" name="wistia_embed" allowfullscreen mozallowfullscreen webkitallowfullscreen oallowfullscreen msallowfullscreen width="640" height="360"></iframe><script src="//fast.wistia.net/assets/external/iframe-api-v1.js"></script>
      <p>Thumbnail two caption...</p>
    </div>

  </li>

</ul>

<div class="box effect2">
  <h3>Effect 2</h3>
</div>

    </div>
  </div>
</div>

app/views/pages/videos.html.erb
<div class="tabbable tabs-left"> <!-- Only required for left/right tabs -->
  <ul class="nav nav-tabs">
    <li class="active"><a href="#tab1" data-toggle="tab">The Basics</a></li>
    <li><a href="#tab2" data-toggle="tab">Section 2</a></li>
    <li><a href="#tab3" data-toggle="tab">Section 3</a></li>
  </ul>
  <div class="tab-content">
    <div class="tab-pane active" id="tab1">
      <div class="page-header">
      <h1>The Basics <p><small>Here's where we'll look at the simple stuff</small></p></h1>
      </div>

      <p>I'm in Section 1.</p>

      <ul class="thumbnails">
        <li class="span3">
          <a href="blah" class="thumbnail">
            <img data-src="holder.js/300x200" alt="">
            <iframe src="https://fast.wistia.net/embed/iframe/l8emkgdbny?videoFoam=true" allowtransparency="true" frameborder="0" scrolling="no" class="wistia_embed" name="wistia_embed" allowfullscreen mozallowfullscreen webkitallowfullscreen oallowfullscreen msallowfullscreen width="640" height="360"></iframe>
            <script src="//fast.wistia.net/assets/external/iframe-api-v1.js"></script>
            <h3>Thumbnail label</h3>
            <p>Thumbnail caption...</p>
          </a>
        </li>
        <li class="span3">
          <a href="blah" class="thumbnail">
            <img data-src="holder.js/300x200" alt="What">
            <h3>Thumbnail label</h3>
            <p>Thumbnail caption...</p>
          </a>
        </li>
        <li class="span3">
          <a href="blah" class="thumbnail">
            <img data-src="holder.js/300x200" alt="What">
            <h3>Thumbnail label</h3>
            <p>Thumbnail caption...</p>
          </a>
        </li>
      </ul>

    </div>

    <div class="tab-pane" id="tab2">
      <p>Howdy, I'm in Section 2.</p>
    </div>
    <div class="tab-pane" id="tab3">
      <p>Just guessin now.</p>
    <div>
  </div>
</div>